### ISSUE TITLE
It seems that "nullable" is not supported?

### ISSUE THREAD

**Issue by nicomuschert** [Zooz/api-contract-validator#29]
Thanks for that great validator!
I just notice that "nullable" does not work.

Jest output:
```
Object {
    -         "timezone": "should be string",
    +         "timezone": null,
            }
```

My declaration:
```
timezone:
        type: string
        x-example: Europe/Berlin
        nullable: true
```

Thanks,
Nico

**Comment by kobik** [comment]
Thanks for the feedback @nicomuschert!

There is an open issue about that in api-schema-builder that is being used for validating the responses https://github.com/Zooz/api-schema-builder/issues/22.

As I'm currently on vacation I won't be able to fix it for the next couple of weeks. But PRs are always welcomed 🙂

Kobi

**Comment by kobik** [comment]
Hi @nicomuschert,

I believe that the best workaround for now would be by passing null as a possible type
```yaml
timezone:
  type:
    - 'string'
    - 'null'
```
